name: build and test

on:
  push:
  pull_request:
    branches: [ main, develop ]
    paths:
    - '**.cs'
    - '**.csproj'

env:
  DOTNET_VERSION: '6.0.401' # The .NET SDK version to use

jobs:
  build:

    name: build-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install dependencies
      working-directory: ./MaterialObligatorio/Implementacion/Codigo/Backend
      run: dotnet restore
      
    - name: Build
      working-directory: ./MaterialObligatorio/Implementacion/Codigo/Backend/PharmaGo.WebApi
      run: dotnet build --configuration Release --no-restore

  test:

    name: test-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install dependencies
      working-directory: ./MaterialObligatorio/Implementacion/Codigo/Backend
      run: dotnet restore
      
    - name: Build
      working-directory: ./MaterialObligatorio/Implementacion/Codigo/Backend/PharmaGo.WebApi
      run: dotnet build --configuration Release --no-restore
    
    - name: Test API
      working-directory: ./MaterialObligatorio/Implementacion/Codigo/Backend/PharnaGo.Test/WebApi.Test
      run: dotnet test --no-build --verbosity normal
    
    - name: Test Business Logic
      working-directory: ./MaterialObligatorio/Implementacion/Codigo/Backend/PharnaGo.Test/BusinessLogic.Test
      run: dotnet test --no-build --verbosity normal

    - name: Test Data Access
      working-directory: ./MaterialObligatorio/Implementacion/Codigo/Backend/PharnaGo.Test/DataAccess.Test
      run: dotnet test --no-build --verbosity normal