name: Build .NET 5.0 Web API

on:
  push:
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [16.x]
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v3
    
    - name: Install npm dependencies
      run: npm ci
      working-directory: ./MaterialObligatorio/Implementacion/Codigo/Frontend

    - name: Build Angular App
      run: npm run build
      working-directory: ./MaterialObligatorio/Implementacion/Codigo/Frontend